default_platform(:ios)

platform :ios do
  desc "Build and upload for a given environment"
  lane :release do |options|
    env = options[:env] || "production"  # default to production if no env provided

    # Run your switch-env.sh script with the environment argument
    sh "../../switch-env.sh #{env}"

    # Now build your app (adjust scheme and export_method as needed)
    build_app(
      scheme: "WireGuardiOS",
      export_method: "app-store"
    )

    # Upload to TestFlight or App Store Connect
    upload_to_testflight
  end
end
