default_platform(:ios)

platform :ios do
  desc "Build and upload dc environment to TestFlight"
  lane :dc do
    # Switch environment via your script
    sh("../../switch-env.sh dc")

    get_certificates
    get_provisioning_profile(app_identifier: "io.jimber.networkisolation.dc")
    get_provisioning_profile(app_identifier: "io.jimber.networkisolation.dc.network-extension")
    # Build app with manual signing, no match or cert calls
    build_app(
      scheme: "WireGuardiOS",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "io.jimber.networkisolation.dc" => "Provisioning SASE DC",
          "io.jimber.networkisolation.dc.network-extension" => "Prov SASE DC NetExt"
        }
      }
    )

    # Upload to TestFlight
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
