default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Set version and build number first
    increment_version_number(version_number: "1.2.0")
    increment_build_number(build_number: Time.now.strftime("%Y%m%d%H%M"))

    # Then build
    build_app(
      scheme: "WireGuardiOS"
    )

    # Upload
    upload_to_testflight
  end
end
